name: Build and deploy Tests unitaires
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Test unitaire API
        run: pytest ./Tests_unitaires/Pytest_unitaire_test_functions_preprocessing.py

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Upload artifact for deployment jobs
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: Déployer sur Render
        run: |
          render deploy --secret RENDER_API_KEY=${{ secrets.RENDER_API_KEY }}
